// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4VWw2IG0pNHflTvierQBpcwALysqYRRY',
    appId: '1:403425224728:web:21f3c6792ed764f4a1fb6d',
    messagingSenderId: '403425224728',
    projectId: 'fir-chat-5981c',
    authDomain: 'fir-chat-5981c.firebaseapp.com',
    storageBucket: 'fir-chat-5981c.appspot.com',
    measurementId: 'G-GQHENTQREV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-2zLV0qOqbPLKlK010Ni6Nn2KecBK5HY',
    appId: '1:403425224728:android:d084f7dcb9c27f28a1fb6d',
    messagingSenderId: '403425224728',
    projectId: 'fir-chat-5981c',
    storageBucket: 'fir-chat-5981c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsSIWrn2ba6mSIqkqH8_E9KUZMUB00H1Y',
    appId: '1:403425224728:ios:6c271654628562bca1fb6d',
    messagingSenderId: '403425224728',
    projectId: 'fir-chat-5981c',
    storageBucket: 'fir-chat-5981c.appspot.com',
    iosBundleId: 'com.example.messagingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBsSIWrn2ba6mSIqkqH8_E9KUZMUB00H1Y',
    appId: '1:403425224728:ios:6c271654628562bca1fb6d',
    messagingSenderId: '403425224728',
    projectId: 'fir-chat-5981c',
    storageBucket: 'fir-chat-5981c.appspot.com',
    iosBundleId: 'com.example.messagingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB4VWw2IG0pNHflTvierQBpcwALysqYRRY',
    appId: '1:403425224728:web:880c6bcbd59755a3a1fb6d',
    messagingSenderId: '403425224728',
    projectId: 'fir-chat-5981c',
    authDomain: 'fir-chat-5981c.firebaseapp.com',
    storageBucket: 'fir-chat-5981c.appspot.com',
    measurementId: 'G-70PPTH0PVJ',
  );
}
